### ISSUE TITLE
회원가입 DB 오류를 수정한다.

### ISSUE THREAD

**Issue by headF1rst** [headF1rst/promisor#20]
회원가입 api 호출 후, 회원가입 인증 api를 호출하지 않았음에도 DB에 회원정보가 저장되어있다.

이메일 인증 유효 시간인 15분이 지나고 인증 메일을 재전송해도 이미 DB에 회원정보가 저장하기 때문에 다시 인증 메일을 통해 회원가입하는게 불가능.

**Comment by juy4556** [comment]
굿입니다.
